import React from "react";
const DATA = {
  success: true,
  data: {
    stats: {
      present: 72,
      absent: 12,
      late: 6,
      earlyout: 0,
      leave: 0,
      shortleave: 0,
      attach: 0,
      offday: 0,
      holidays: 0,
      night_shift: 0,
      no_time_category: 1,
    },
    total_departmental_employees: 90,
    deptStats: {
      Labors: 48,
      Administration: 20,
      "Labors Soap": 8,
      "Internship Employees": 2,
    },
    deptStatsDetail: {
      Labors: {
        present: 48,
        absent: 8,
        late: 2,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
      "Labors Soap": {
        present: 8,
        absent: 2,
        late: 0,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
      Administration: {
        present: 20,
        absent: 1,
        late: 4,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },

      Labor: {
        present: 48,
        absent: 8,
        late: 2,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
      "Internship Employees": {
        present: 2,
        absent: 0,
        late: 0,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
      Labr: {
        present: 48,
        absent: 8,
        late: 2,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
      "Hamza Hassan Detergents & Soap (SMC-Pvt) Ltd.": {
        present: 0,
        absent: 1,
        late: 0,
        leave: 0,
        shortleave: 0,
        attach: 0,
        offday: 0,
        holidays: 0,
        night_shift: 0,
      },
    },
    desigStats: {
      Labor: 54,
      Chemist: 2,
      "Sales Department": 4,
      Purchaser: 1,
      "Operation Manager": 1,
      "Gate keeper": 2,
      Assistant: 4,
      Administrative: 3,
      Supervisor: 1,
      Finance: 3,
      "Warehouse manager": 2,
      "Inventory manager": 1,
    },
    drilldown_data: {
      present: [
        {
          id: 3709486,
          user_id: 149,
          name: "Ashraf Ali",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:09:04",
          timeout: "08:09:04",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709487,
          user_id: 150,
          name: "Muhammad Rafiq",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:10:20",
          timeout: "08:10:20",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709488,
          user_id: 355,
          name: "Haseeb Ullah(Peer Gul)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:59:49",
          timeout: "07:59:49",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709490,
          user_id: 395,
          name: "Said Nabi",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:09:24",
          timeout: "08:09:24",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709491,
          user_id: 930,
          name: "Gul Zar Khan Sales Office",
          department: "Administration",
          designation: "Sales Department",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:17:53",
          timeout: "18:00:44",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709492,
          user_id: 931,
          name: "Zahoor Khan Sales Office",
          department: "Administration",
          designation: "Sales Department",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:05:28",
          timeout: "18:01:31",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709494,
          user_id: 944,
          name: "Shamim",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:49:37",
          timeout: "07:49:37",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709495,
          user_id: 948,
          name: "Saraj Uddin Safi",
          department: "Administration",
          designation: "Operation Manager",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "04:47:48",
          timeout: "18:14:01",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709496,
          user_id: 950,
          name: "Muhammad Sadiq",
          department: "Administration",
          designation: "Sales Department",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "07:34:34",
          timeout: "18:01:38",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709498,
          user_id: 1121,
          name: "Muhammad Umair",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:02:21",
          timeout: "08:02:21",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709499,
          user_id: 1123,
          name: "Hijrat Ullah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:10:26",
          timeout: "08:10:26",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709500,
          user_id: 1124,
          name: "Muhammad Adnan",
          department: "Administration",
          designation: "Gate keeper",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:36:07",
          timeout: "07:36:07",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709501,
          user_id: 1580,
          name: "S Usama Shakir",
          department: "Administration",
          designation: "Assistant",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "08:23:26",
          timeout: "00:00:00",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709502,
          user_id: 1634,
          name: "Bismillah jan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:11:33",
          timeout: "08:11:33",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709503,
          user_id: 1671,
          name: "Hameed",
          department: "Administration",
          designation: "Administrative",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:07:07",
          timeout: "18:03:38",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709504,
          user_id: 35609,
          name: "Tariq",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:47:49",
          timeout: "07:47:49",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709505,
          user_id: 35610,
          name: "Abdul Rauf",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:58:50",
          timeout: "07:58:50",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709506,
          user_id: 35611,
          name: "Khalid",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:08:08",
          timeout: "08:08:08",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709507,
          user_id: 35612,
          name: "Abdul Kareem (Mula Jan)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:49:17",
          timeout: "07:49:17",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709508,
          user_id: 35614,
          name: "Shahzad",
          department: "Administration",
          designation: "Supervisor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:11:24",
          timeout: "08:11:24",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709509,
          user_id: 35615,
          name: "Mudasir",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:15:31",
          timeout: "08:15:31",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709510,
          user_id: 35624,
          name: "Murad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:24:25",
          timeout: "07:24:25",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709511,
          user_id: 35625,
          name: "Bakhtawar Shah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:57:15",
          timeout: "07:57:15",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709512,
          user_id: 35626,
          name: "Omar Hafiz Ullah",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:57:37",
          timeout: "07:57:37",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709513,
          user_id: 36016,
          name: "Momin Khan",
          department: "Administration",
          designation: "Administrative",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:15:29",
          timeout: "18:15:20",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709514,
          user_id: 36018,
          name: "Afzaal Khan",
          department: "Administration",
          designation: "Administrative",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:00:03",
          timeout: "18:00:05",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709515,
          user_id: 36023,
          name: "Nawid khan",
          department: "Administration",
          designation: "Finance",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:17:35",
          timeout: "18:11:38",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709517,
          user_id: 37240,
          name: "Mnawr khan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:01:08",
          timeout: "08:01:08",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709518,
          user_id: 37243,
          name: "Elyas",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:48:28",
          timeout: "07:48:28",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709519,
          user_id: 37244,
          name: "Adil",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:48:45",
          timeout: "07:48:45",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709520,
          user_id: 37247,
          name: "Niaz Men",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:59:56",
          timeout: "07:59:56",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709521,
          user_id: 37249,
          name: "Abdul raziq",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:49:24",
          timeout: "07:49:24",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709522,
          user_id: 37251,
          name: "Riaz khan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:47:38",
          timeout: "07:47:38",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709523,
          user_id: 37252,
          name: "Abdul karim (Rehman)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:12:52",
          timeout: "08:12:52",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709524,
          user_id: 37253,
          name: "Zubir",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:07:54",
          timeout: "08:07:54",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709525,
          user_id: 37255,
          name: "Irfan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:55:37",
          timeout: "07:55:37",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709526,
          user_id: 37261,
          name: "Khan muhammad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:34:45",
          timeout: "07:34:45",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709527,
          user_id: 37262,
          name: "Faiz muhammad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:01:56",
          timeout: "08:01:56",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709528,
          user_id: 37264,
          name: "Shubhan ullah",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:09:28",
          timeout: "08:09:28",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709531,
          user_id: 37277,
          name: "Muhammad Amir",
          department: "Administration",
          designation: "Assistant",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "08:55:42",
          timeout: "17:55:50",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709532,
          user_id: 37278,
          name: "Ramiz Jalil",
          department: "Administration",
          designation: "Gate keeper",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "07:46:47",
          timeout: "18:36:12",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709534,
          user_id: 37291,
          name: "Zubair Ahmad",
          department: "Administration",
          designation: "Inventory manager",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:06:46",
          timeout: "17:58:26",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709535,
          user_id: 37296,
          name: "Adnan Raqib",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:57:25",
          timeout: "07:57:25",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709536,
          user_id: 37326,
          name: "Naik noor",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:00:03",
          timeout: "08:00:03",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709537,
          user_id: 37502,
          name: "Anwar ali",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:57:31",
          timeout: "07:57:31",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709538,
          user_id: 37504,
          name: "Bilal Abdullah",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:50:47",
          timeout: "07:50:47",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709539,
          user_id: 37558,
          name: "Faiz ullah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:47:44",
          timeout: "07:47:44",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709541,
          user_id: 37576,
          name: "Zahir",
          department: "Labors",
          designation: "Assistant",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "08:24:50",
          timeout: "00:00:00",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709543,
          user_id: 37911,
          name: "Amir Khan(A.B Rasheed)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:07:12",
          timeout: "08:07:12",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709544,
          user_id: 37912,
          name: "Badam Gul",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:50:25",
          timeout: "07:50:25",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709545,
          user_id: 37913,
          name: "Javaid",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:55:43",
          timeout: "07:55:43",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709546,
          user_id: 37916,
          name: "Safi Ullah",
          department: "Administration",
          designation: "Sales Department",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "06:50:09",
          timeout: "18:03:29",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709547,
          user_id: 37919,
          name: "Sifat Ullah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:00:40",
          timeout: "08:00:40",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709549,
          user_id: 37923,
          name: "Abdullah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:57:51",
          timeout: "07:57:51",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709550,
          user_id: 38298,
          name: "Haseeb Rehman",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:47:25",
          timeout: "07:47:25",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709551,
          user_id: 38559,
          name: "Awaz Khan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:49:10",
          timeout: "07:49:10",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709552,
          user_id: 38736,
          name: "Salman",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:49:46",
          timeout: "07:49:46",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709553,
          user_id: 38792,
          name: "Arbab Haidar Ali",
          department: "Administration",
          designation: "Finance",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:02:55",
          timeout: "17:25:30",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709555,
          user_id: 39006,
          name: "Mohammad Afaq",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:13:03",
          timeout: "08:13:03",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709556,
          user_id: 39018,
          name: "Mumtaz Khan",
          department: "Labors",
          designation: "Assistant",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "07:51:50",
          timeout: "18:45:19",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709557,
          user_id: 39041,
          name: "Abdullah (Chamani)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:01:42",
          timeout: "08:01:42",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709558,
          user_id: 39042,
          name: "Abuzar Khan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:02:42",
          timeout: "08:02:42",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709559,
          user_id: 39052,
          name: "Esmatullah",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:03:15",
          timeout: "08:03:15",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709560,
          user_id: 39056,
          name: "Mohammad Omar (Ishrat Khan)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:54:32",
          timeout: "07:54:32",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709561,
          user_id: 39158,
          name: "Adnan Khan (Bakhtawar)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:55:06",
          timeout: "07:55:06",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709562,
          user_id: 39159,
          name: "Hameeullah(Cook)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:09:19",
          timeout: "08:09:19",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709563,
          user_id: 39160,
          name: "Gul Mohammad (Cook)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:17:43",
          timeout: "08:17:43",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709564,
          user_id: 39173,
          name: "Izat Gul",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:03:54",
          timeout: "08:03:54",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709565,
          user_id: 39174,
          name: "Yaad Gul",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:50:14",
          timeout: "07:50:14",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709567,
          user_id: 39229,
          name: "Mohammad Adnan (Hanif)",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "07:50:37",
          timeout: "07:50:37",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709570,
          user_id: 41260,
          name: "Mohammad Kaleemullah",
          department: "Internship Employees",
          designation: "Finance",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "08:42:15",
          timeout: "17:58:21",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709571,
          user_id: 41323,
          name: "Uzairr Ahmad",
          department: "Internship Employees",
          designation: "Warehouse manager",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "08:59:19",
          timeout: "17:58:16",
          status: "present",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
      ],
      absent: [
        {
          id: 3709483,
          user_id: 145,
          name: "Fazal Karim",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709484,
          user_id: 147,
          name: "Taimur khan",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709497,
          user_id: 1119,
          name: "Hazrat Omar",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709516,
          user_id: 36033,
          name: "Muhammad Yasin",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709540,
          user_id: 37562,
          name: "Gul Muhammad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709542,
          user_id: 37908,
          name: "Adnan zamin",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709548,
          user_id: 37920,
          name: "Shafi Ullah",
          department: "Labors Soap",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709554,
          user_id: 38829,
          name: "Farhad Ullah",
          department: "Administration",
          designation: "Supervisor",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709566,
          user_id: 39219,
          name: "Mohammad Nawshad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709568,
          user_id: 39251,
          name: "Jawas Khan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709569,
          user_id: 39252,
          name: "Said Ali Jan",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709572,
          user_id: 499288581,
          name: "Hamza Hassan Detergents & Soap (SMC-Pvt) Ltd.",
          department: "Hamza Hassan Detergents & Soap (SMC-Pvt) Ltd.",
          designation: null,
          date: "2026-08-05",
          tcat_id: 0,
          tcat_in: "00:00:00",
          tcat_out: "00:00:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "No Time Category Assigned",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
      ],
      late: [
        {
          id: 3709485,
          user_id: 148,
          name: "Amir noor muhammad",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:53:12",
          timeout: "00:00:00",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709489,
          user_id: 361,
          name: "Qari Fazal Rabi",
          department: "Administration",
          designation: "Chemist",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "09:23:49",
          timeout: "18:03:44",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709493,
          user_id: 936,
          name: "Shoaib Akhtar",
          department: "Administration",
          designation: "Purchaser",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "11:01:42",
          timeout: "18:01:46",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709529,
          user_id: 37268,
          name: "Rashid",
          department: "Labors",
          designation: "Labor",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:27:01",
          timeout: "08:27:01",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709530,
          user_id: 37276,
          name: "Surab Khan",
          department: "Administration",
          designation: "Warehouse manager",
          date: "2026-08-05",
          tcat_id: 3995,
          tcat_in: "09:00:00",
          tcat_out: "18:00:00",
          night_shift: 0,
          timein: "10:46:31",
          timeout: "17:59:03",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
        {
          id: 3709533,
          user_id: 37281,
          name: "Mubin jalil",
          department: "Administration",
          designation: "Chemist",
          date: "2026-08-05",
          tcat_id: 5003,
          tcat_in: "08:00:00",
          tcat_out: "05:30:00",
          night_shift: 0,
          timein: "08:34:29",
          timeout: "00:00:00",
          status: "late",
          remarks: "",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
      ],
      earlyout: [],
      leave: [],
      shortleave: [],
      attach: [],
      offday: [],
      holidays: [],
      night_shift: [],
      no_time_category: [
        {
          id: 3709572,
          user_id: 499288581,
          name: "Hamza Hassan Detergents & Soap (SMC-Pvt) Ltd.",
          department: "Hamza Hassan Detergents & Soap (SMC-Pvt) Ltd.",
          designation: null,
          date: "2026-08-05",
          tcat_id: 0,
          tcat_in: "00:00:00",
          tcat_out: "00:00:00",
          night_shift: 0,
          timein: "00:00:00",
          timeout: "00:00:00",
          status: "absent",
          remarks: "No Time Category Assigned",
          created_at: null,
          updated_at: null,
          deleted_at: null,
        },
      ],
    },
    online_devices_count: 1,
    offline_devices_count: 0,
    online_offline_devices: [
      {
        id: null,
        serialno: null,
        description: "H-H ",
        state: 1,
        lastactivity: "2026-08-05 18:52:16",
        created_time: null,
        transtimes: null,
        transinternal: null,
        logstamp: "9999",
        oplogstamp: "9999",
        alias: null,
        deptid: null,
        updatedb: null,
        style: null,
        fwversion: "ZAM180-NF28VA-Ver3.0.42",
        fpcount: 10,
        transactioncount: 41171,
        usercount: 132,
        maintime: "1970-01-01 00:00:00",
        maxfingercount: 30,
        maxattlogcount: 10,
        devicename: "MB560-VL",
        algver: "10",
        flashsize: "5458248",
        freeflashsize: "5168824",
        language: "69",
        volume: "70",
        dtfmt: "9",
        ipaddress: "192.168.18.23",
        istft: null,
        platform: "FAM180_TFT",
        brightness: "0",
        backupdev: null,
        manufacturer: "ZKTECO CO., LTD.",
        city: null,
        accfun: null,
        tzadj: 5,
        deltag: null,
        photostamp: null,
        ftfpversion: "10",
        deviceid: 0,
        userid: null,
        defaultdeptid: null,
        name: null,
        password: null,
        cardnumber: null,
        privilege: null,
        accgroup: null,
        timezone: null,
        dev_serial: "HWM4244200041",
        online_status: 1,
        users_count: 0,
      },
    ],
  },
};

export default DATA;
